trainer: 'finetune'
args:
    seed: 0
    model_name: 'roberta-large'
    train: 'data/SuperFUGUE/RTE/train.jsonl'
    dev: 'data/SuperFUGUE/RTE/dev.jsonl'
    test: 'data/SuperFUGUE/RTE/dev_all.jsonl'
    checklist: null
    template: '{sentence2} [T] [T] [P] [T] {sentence1}'
    label_map: '{"entailment": "Yes", "Not_entailment": "No"}'
    label_field: 'label'
    preprocessor: null 
    evaluation_strategy: 'classification'
    finetune_mode: []
    evaluation_metric: 'accuracy'
    skip_train: False
    skip_eval: False
    skip_test: False
    bsz: 2
    epochs: 30
    disable_dropout: False
    clip: 1.0
    limit: null
    force_overwrite: True
    quiet: False
    tmp: True
parameters:
    accumulation_steps: [1, 2, 4]
    lr: [1.0e-5, 5.0e-5, 1.0e-4, 5.0e-4]
