version: 2
jobs:
    build:
        working_directory: ~/autoprompt
        docker:
            - image: continuumio/miniconda3
        environment:
            OMP_NUM_THREADS: 1
        resource_class: medium
        parallelism: 1
        steps:
            - checkout
            - run: conda install pytorch cpuonly -c pytorch
            - run: pip install -e '.[test]'
            - run: python -m pytest --disable-warnings
            - store_test_results:
                path: test-results
        
